package dop.chapter05;

import dop.chapter05.the.existing.world.Annotations.*;
import dop.chapter05.the.existing.world.Entities.Address;

import jakarta.annotation.Nullable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Currency;
import java.util.List;

public class Listing5_2 {

  /**
   * ───────────────────────────────────────────────────────
   * Listing 5.2
   * ───────────────────────────────────────────────────────
   * The bedrock set of identity objects on which our application
   * is built. These are playing the role of "what's already there"
   * in our pretend application.
   *
   * Getters, setters, etc are omitted for brevity. (Assume they're
   * auto-generated by the (made up) annotation processor)
   */
  enum InvoiceType {LATEFEE, STANDARD};   // ◄── This enum tells us what kind of Invoice the Invoice Entity is representing
  enum InvoiceStatus {OPEN, CLOSED}

  @Entity   //  ◄───────────────────┐
  class Invoice {            //     │
    @ID  //  ◄──────────────────────│ (These annotations are made up. Assume they allow our imagined ORM
    String invoiceId;        //     │ to automatically serialize objects to/from storage )
    String customerId;       //     │
    @ManyToOne  //  ◄───────────────┘
    List<LineItem> lineItems;
    InvoiceStatus status;
    LocalDate invoiceDate;
    LocalDate dueDate;
    InvoiceType type;
    @Nullable
    AuditInfo auditInfo;  // ◄── This will be populated when InvoiceType is LATEFEE, otherwise null
  }

  @Entity
  class LineItem {
    @ID
    String id;
    String description;
    BigDecimal charges;   // ◄────┐ Built in Java types are used on these core entities rather
    Currency currency;    //      │ than more data-oriented ones. ORMs usually make customizing
  }                       //      │ types tedious enough that most won’t bother.

  @Entity
  class AuditInfo {
    @ID
    @OneToOne
    String invoiceId;
    @ManyToMany
    List<Invoice> includedInFee;
    @Nullable
    String cannotBillReason;
  }

  @Entity
  class Customer {             // ◄── The canonical Customer entity
    @ID
    String customerId;
    Address address;
    @Nullable
    String approvalId;         // ◄── Approval ID is tracked here for “ease”
  }

}
