/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dop;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello from Data Oriented Java!");
    }
}
